Create wick3dr0se.json
opensource-force/hackathon-1 pull request #4
Opened 2023-07-27 01:40 UTC by wick3dr0se

2023-07-27 01:57 UTC, akpi816218 requested changes, later dismissed
Change path to schema

2023-07-27 01:57 UTC, akpi816218 commented on projects/wick3dr0se.json
> +	"$schema": "./project.schema.json",
Change to `../` please!

2023-07-27 03:02 UTC, akpi816218 requested changes

2023-07-27 03:02 UTC, akpi816218 commented on projects/wick3dr0se.json
> +	"$schema": "./wick3dr0se.json",
`../project.schema.json`

2023-07-27 03:11 UTC, wick3dr0se reviewed
Thanks 😅

2023-07-27 03:12 UTC, wick3dr0se reviewed
Updated

2023-07-27 03:12 UTC, merged

2023-07-31 15:40 UTC, akpi816218 approved these changes